export default {
  messages: {
    APPLICATION_TITLE: "UNI10",
    WELCOME_TO_UNI10: "Welcome to UNI10",
    LOGIN: "Login",
    REGISTER: "Register",
    LET_S_START: "LET'S START",
    LET_S_GO: "LET'S GO",
    CHANGE_PASSWORD: "Schimbare parola",
    RESET_PASSWORD: "Reseteaza parola",
    HELLO: "Salut",
    WELCOME: "Bine ai venit",
    NEWS: "Noutati",
    PROFILE: "Profil",
    COURSES: "Cursuri",
    SEMINARIES: "Seminarii",
    LABORATORIES: "Laboratoare",
    TIMETABLE: "Orar",
    TAKE_A_LOOK_TO_COURSES: "Arunca o privire peste materiile disponibile!",
    WHAT_WILL_YOU_STUDY_TODAY: "Ce vei studia astazi?",
    YOU_CAN_UPLOAD_FILES: "Vei putea incarca materiale utile pentru cursuri, seminarii sau laboratoare!",
    YEAR: "Anul",
    WHATS_NEW: "Ce e nou",
    COMMENTS: "Comentarii",
    USEFUL_LINKS: "Link-uri utile",
    INCORECT_PASSWORDS: "Cele doua parole sunt diferite. Incearca din nou",
      ERROR_MESSAGE: "Eroare",
      CLOSE_BUTTON:"Inchide"
  }
};
